### PR TITLE
feat: make it smaller

### PR DESCRIPTION
**Pull request by hugomrdias**
clean up a bit package.json
add node 8 and 10 to travis
removes polyfills
removes unused vars and functions

### CODE REVIEW

**Comment by hugomrdias** [comment]
Ping

**Comment by hugomrdias** [comment]
@maxogden @mafintosh any chance we can get this merged and released ?

**Comment by jimmywarting** [comment]
Did the same thing in #63 + a bit more without realising you hade already done some of it

**Comment by alanshaw** [comment]
🙏 🥺 please can we have?

**Comment by max-mapper** [comment]
@alanshaw added you as a maintainer because I know you IRL :) I'd recommend the next npm publish be a major version just to avoid any potential breakage since this is so widely used

**Comment by martinheidegger** [comment]
@alanshaw @hugomrdias Would it be possible to add `buffer` as a dependency to the package.json? _(and a `var Buffer = require('buffer')` statement)_ to make sure that [no extra setup](https://webpack.js.org/configuration/node/) is needed in webpack context?

**Pull request closed without merging**
